# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  lanches:
    image: lanches
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5036:5036
    environment:
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    networks:
      - web-dev

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    networks:
      - web-dev
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - web-dev
      

networks:
  web-dev:
    driver: bridge

volumes:
  db_data: {}  